<?php

namespace App\Database\Firebird\Schema\Grammars;

use HarryGulliford\Firebird\Schema\Grammars\FirebirdGrammar as BaseFirebirdGrammar;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Fluent;

class FirebirdGrammar extends BaseFirebirdGrammar
{
    /**
     * Get the SQL for an increment column modifier.
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $column
     * @return string|null
     */
    protected function modifyIncrement(Blueprint $blueprint, Fluent $column)
    {
        if (in_array($column->type, $this->serials) && $column->autoIncrement) {
            return ' GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
        }
    }
}
